/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

/**
 *
 * @author ASUS
 */
public class konversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public konversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCelcius = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        textCelcius = new javax.swing.JTextField();
        buttonConvert = new javax.swing.JButton();
        labelCelciuus = new javax.swing.JLabel();
        labelFarenheit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konversi Suhu");
        setForeground(new java.awt.Color(255, 255, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        buttonConvert.setBackground(new java.awt.Color(0, 102, 255));
        buttonConvert.setForeground(new java.awt.Color(255, 255, 51));
        buttonConvert.setText("Convert");
        buttonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConvertActionPerformed(evt);
            }
        });
        buttonConvert.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonConvertKeyPressed(evt);
            }
        });

        labelCelciuus.setBackground(new java.awt.Color(0, 0, 0));
        labelCelciuus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelCelciuus.setText("Celcius");

        labelFarenheit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelFarenheit.setText("0 Fahrenheit");
        labelFarenheit.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                labelFarenheitAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textCelcius)
                    .addComponent(buttonConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFarenheit)
                    .addComponent(labelCelciuus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCelciuus)
                    .addComponent(textCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonConvert)
                    .addComponent(labelFarenheit))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout labelCelciusLayout = new javax.swing.GroupLayout(labelCelcius);
        labelCelcius.setLayout(labelCelciusLayout);
        labelCelciusLayout.setHorizontalGroup(
            labelCelciusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        labelCelciusLayout.setVerticalGroup(
            labelCelciusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelCelciusLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCelcius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCelcius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConvertActionPerformed
        //ambil isi text dari object textCelcius
        String strCelcius = textCelcius.getText();
        //ubah dari text atau string celcius menjadi variable dengan type double
        // supaya dapat diproses aritmatika
        double celcius = Double.valueOf(strCelcius);
        //proses conversi dari celcius ke fahrenheit dengan rumus celcius * 1.8+32
        double fahrenheit = celcius * 1.8 +32;
        //tampilkan hasil fahrenheit pada label fahrenheit
        labelFarenheit.setText(fahrenheit + " Fahrenheit");
    }//GEN-LAST:event_buttonConvertActionPerformed

    private void buttonConvertKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonConvertKeyPressed
         String strCelcius = textCelcius.getText();
        //ubah dari text atau string celcius menjadi variable dengan type double
        // supaya dapat diproses aritmatika
        double celcius = Double.valueOf(strCelcius);
        //proses conversi dari celcius ke fahrenheit dengan rumus celcius * 1.8+32
        double fahrenheit = celcius * 1.8 +32;
        //tampilkan hasil fahrenheit pada label fahrenheit
        labelFarenheit.setText(fahrenheit + "Fahrenheit");
    }//GEN-LAST:event_buttonConvertKeyPressed

    private void labelFarenheitAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_labelFarenheitAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_labelFarenheitAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConvert;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel labelCelcius;
    private javax.swing.JLabel labelCelciuus;
    private javax.swing.JLabel labelFarenheit;
    private javax.swing.JTextField textCelcius;
    // End of variables declaration//GEN-END:variables
}
