/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class panelKalkulatorDuaAngka extends javax.swing.JPanel {

    /**
     * Creates new form panelKalkulatorDuaAngka
     */
    public panelKalkulatorDuaAngka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textAngkaPertama = new javax.swing.JTextField();
        textAngkaKedua = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonKurang = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonBagi = new javax.swing.JButton();
        buttonKali = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        operator = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Aplikasi Kalkulator Sedeerhana"));

        textAngkaPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAngkaPertamaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("=");

        buttonKurang.setText("Kurang");
        buttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangActionPerformed(evt);
            }
        });

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonBagi.setText("Bagi");
        buttonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBagiActionPerformed(evt);
            }
        });

        buttonKali.setText("Kali");
        buttonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaliActionPerformed(evt);
            }
        });

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        operator.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        operator.setText("+");

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textAngkaPertama, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(operator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textAngkaKedua, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonTambah)
                        .addGap(9, 9, 9)
                        .addComponent(buttonKurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(buttonBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonKeluar)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAngkaPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAngkaKedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(operator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKurang)
                    .addComponent(buttonBagi)
                    .addComponent(buttonKali)
                    .addComponent(buttonKeluar)
                    .addComponent(buttonTambah)
                    .addComponent(jButton1))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKurangActionPerformed
        proseskurang();
    }//GEN-LAST:event_buttonKurangActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
       prosestambah();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBagiActionPerformed
        prosesBagi();
    }//GEN-LAST:event_buttonBagiActionPerformed

    private void buttonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaliActionPerformed
        prosesKali();
       
    }//GEN-LAST:event_buttonKaliActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        proseskeluar();
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        proseshapus();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textAngkaPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAngkaPertamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAngkaPertamaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBagi;
    private javax.swing.JButton buttonKali;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonKurang;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel operator;
    private javax.swing.JTextField textAngkaKedua;
    private javax.swing.JTextField textAngkaPertama;
    // End of variables declaration//GEN-END:variables

    private void prosestambah() {
        
        operator.setText(" + ");
        String strAngkaPertama = textAngkaPertama.getText();
        String strAngkaKedua = textAngkaKedua.getText();
        if(isNull(strAngkaPertama)|| isNull(strAngkaKedua)){
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Mohon isi semua field","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
             int angkaPertama = Integer.valueOf(strAngkaPertama);
        int angkaKedua = Integer.valueOf(strAngkaKedua);
        int hasil = angkaPertama + angkaKedua;
        this.hasil.setText(hasil + "");
        }
        
       
    }

    private void proseskurang() {
        operator.setText(" - ");
        String strAngkaPertama = textAngkaPertama.getText();
        String strAngkaKedua = textAngkaKedua.getText();
        if(isNull(strAngkaPertama)|| isNull(strAngkaKedua)){
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Mohon isi semua field","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
             int angkaPertama = Integer.valueOf(strAngkaPertama);
        int angkaKedua = Integer.valueOf(strAngkaKedua);
        int hasil = angkaPertama - angkaKedua;
        this.hasil.setText(hasil + "");
        }
    }

    private void prosesBagi() {
        operator.setText(" / ");
        String strAngkaPertama = textAngkaPertama.getText();
        String strAngkaKedua = textAngkaKedua.getText();
        if(isNull(strAngkaPertama)|| isNull(strAngkaKedua)){
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Mohon isi semua field","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
             int angkaPertama = Integer.valueOf(strAngkaPertama);
        int angkaKedua = Integer.valueOf(strAngkaKedua);
        int hasil = angkaPertama / angkaKedua;
        this.hasil.setText(hasil + "");
        }
    }

    private void prosesKali() {
        operator.setText(" X ");
        String strAngkaPertama = textAngkaPertama.getText();
        String strAngkaKedua = textAngkaKedua.getText();
        if(isNull(strAngkaPertama)|| isNull(strAngkaKedua)){
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Mohon isi semua field","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
             int angkaPertama = Integer.valueOf(strAngkaPertama);
        int angkaKedua = Integer.valueOf(strAngkaKedua);
        int hasil = angkaPertama * angkaKedua;
        this.hasil.setText(hasil + "");
        }
    }

    private void proseskeluar() {
        boolean yakin = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ?", "Konfirmasi", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION;
        if (yakin){
            System.exit(0);
        }
    }

    private void proseshapus() {
        textAngkaPertama.setText("");
        textAngkaKedua.setText("");
        hasil.setText("");
        textAngkaPertama.requestFocus();
    }
    
   private static boolean isNull(String str){
       if(str != null && ! str.isEmpty())
           return false;
       return true;
   }
}
